# Generated by Django 3.0.3 on 2020-03-10 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('runtime', models.IntegerField()),
                ('branch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yoga_page.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('branch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yoga_page.Branch')),
            ],
        ),
    ]
