# Generated by Django 3.0.3 on 2020-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='default utl', max_length=100),
            preserve_default=False,
        ),
    ]
