# Generated by Django 3.0.3 on 2020-03-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_page', '0002_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='images',
            field=models.ImageField(upload_to='branch_image'),
        ),
    ]
