# Generated by Django 3.0.3 on 2020-03-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_page', '0003_auto_20200314_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to='yoga_page/static/images', verbose_name='image'),
        ),
    ]
