# Generated by Django 3.0.3 on 2020-03-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_page', '0003_auto_20200305_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='images',
            field=models.ImageField(upload_to='yoga_image'),
        ),
    ]
