# Generated by Django 3.0.3 on 2020-03-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_page', '0003_auto_20200310_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='branch_images', to='yoga_page.Branch'),
        ),
    ]
