# Generated by Django 3.0.3 on 2020-03-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_page', '0004_auto_20200305_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
