# Generated by Django 3.0.3 on 2020-03-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_page', '0005_auto_20200314_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='translation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
