# Generated by Django 3.0.3 on 2020-03-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_page', '0006_branch_translation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='video_id',
        ),
    ]
